# Goal of this workflow is whenever someone chnages the python code , 
# the linter will check if the syntax , format , indentation ( linting) is correct or not 

name: Auto Linter

on:
  push: 
    paths: "*.py"      # Linter will run when there is any change to python file only

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    #this step will automatically clone the code of the current main branch into the runner and will use the actions uses for that @v7 is the version , kind of will automate git clone command 
      - name: Checkout/clone the code
        uses: actions/checkout@v7
  #this step will install the linting tool pip install ruff is used in python to deal with linter
      - name: Install Linter
        run: pip install ruff
# this step will actually run the linter and check our file
      - name: Check the files for linting
        run: ruff check .
      
    
